"""Move resume_url to job_applications

Revision ID: a4a6486c2183
Revises: 59a12f4010c0
Create Date: 2026-07-09 21:51:56.984710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a6486c2183'
down_revision: Union[str, Sequence[str], None] = '59a12f4010c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('resume_url', sa.String(length=500), nullable=True))
    op.drop_column('users', 'resume_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('resume_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('job_applications', 'resume_url')
    # ### end Alembic commands ###
